# Generated by Django 4.0.5 on 2022-06-28 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='is_like',
        ),
    ]
